export const CONVERTER_CATEGORIES = [
  {
    id: "length",
    label: "Length / Distance",
    units: [
      { id: "m", label: "meter (m)" },
      { id: "km", label: "kilometer (km)" },
      { id: "cm", label: "centimeter (cm)" },
      { id: "mm", label: "millimeter (mm)" },
      { id: "in", label: "inch (in)" },
      { id: "ft", label: "foot (ft)" },
      { id: "yd", label: "yard (yd)" },
      { id: "mi", label: "mile (mi)" },
      { id: "nmi", label: "nautical mile (nmi)" },
    ],
  },
  {
    id: "mass",
    label: "Mass / Weight",
    units: [
      { id: "g", label: "gram (g)" },
      { id: "kg", label: "kilogram (kg)" },
      { id: "mg", label: "milligram (mg)" },
      { id: "lb", label: "pound (lb)" },
      { id: "oz", label: "ounce (oz)" },
      { id: "t", label: "metric ton (t)" },
      { id: "ust", label: "US ton (ust)" },
      { id: "st", label: "stone (st)" },
    ],
  },
  {
    id: "volume",
    label: "Volume / Capacity",
    units: [
      { id: "l", label: "liter (L)" },
      { id: "ml", label: "milliliter (mL)" },
      { id: "m3", label: "cubic meter (m³)" },
      { id: "cm3", label: "cubic centimeter (cm³)" },
      { id: "gal_us", label: "gallon (US)" },
      { id: "gal_uk", label: "gallon (UK)" },
      { id: "qt_us", label: "quart (US)" },
      { id: "pt_us", label: "pint (US)" },
      { id: "cup_us", label: "cup (US)" },
      { id: "floz_us", label: "fluid ounce (US)" },
    ],
  },
  {
    id: "area",
    label: "Area",
    units: [
      { id: "m2", label: "square meter (m²)" },
      { id: "km2", label: "square kilometer (km²)" },
      { id: "cm2", label: "square centimeter (cm²)" },
      { id: "ha", label: "hectare (ha)" },
      { id: "acre", label: "acre" },
      { id: "ft2", label: "square foot (ft²)" },
      { id: "yd2", label: "square yard (yd²)" },
      { id: "mi2", label: "square mile (mi²)" },
    ],
  },
  {
    id: "temperature",
    label: "Temperature",
    units: [
      { id: "c", label: "Celsius (°C)" },
      { id: "f", label: "Fahrenheit (°F)" },
      { id: "k", label: "Kelvin (K)" },
    ],
  },
  {
    id: "time",
    label: "Time",
    units: [
      { id: "s", label: "second (s)" },
      { id: "min", label: "minute (min)" },
      { id: "h", label: "hour (h)" },
      { id: "day", label: "day" },
      { id: "week", label: "week" },
      { id: "month", label: "month (approx.)" },
      { id: "year", label: "year" },
      { id: "decade", label: "decade" },
      { id: "century", label: "century" },
      { id: "millennium", label: "millennium" },
    ],
  },
  {
    id: "speed",
    label: "Speed / Velocity",
    units: [
      { id: "mps", label: "meters per second (m/s)" },
      { id: "kmph", label: "kilometers per hour (km/h)" },
      { id: "mph", label: "miles per hour (mph)" },
      { id: "kn", label: "knots" },
      { id: "fps", label: "feet per second (ft/s)" },
    ],
  },
  {
    id: "energy",
    label: "Energy / Work",
    units: [
      { id: "j", label: "joule (J)" },
      { id: "kj", label: "kilojoule (kJ)" },
      { id: "cal", label: "calorie (cal)" },
      { id: "kcal", label: "kilocalorie (kcal)" },
      { id: "wh", label: "watt-hour (Wh)" },
      { id: "ev", label: "electronvolt (eV)" },
      { id: "btu", label: "British Thermal Unit (BTU)" },
    ],
  },
  {
    id: "power",
    label: "Power",
    units: [
      { id: "w", label: "watt (W)" },
      { id: "kw", label: "kilowatt (kW)" },
      { id: "hp", label: "horsepower (hp)" },
      { id: "btu_h", label: "BTU per hour" },
    ],
  },
  {
    id: "pressure",
    label: "Pressure",
    units: [
      { id: "pa", label: "pascal (Pa)" },
      { id: "kpa", label: "kilopascal (kPa)" },
      { id: "bar", label: "bar" },
      { id: "atm", label: "atmosphere (atm)" },
      { id: "mmhg", label: "millimeters of mercury (mmHg)" },
      { id: "psi", label: "pounds per square inch (psi)" },
    ],
  },
  {
    id: "density",
    label: "Density",
    units: [
      { id: "kgm3", label: "kilogram per cubic meter (kg/m³)" },
      { id: "gcm3", label: "gram per cubic centimeter (g/cm³)" },
      { id: "lbft3", label: "pound per cubic foot (lb/ft³)" },
    ],
  },
  {
    id: "angle",
    label: "Angle",
    units: [
      { id: "deg", label: "degrees (°)" },
      { id: "rad", label: "radians (rad)" },
      { id: "gon", label: "gradians (gon)" },
    ],
  },
  {
    id: "data",
    label: "Data / Digital Information",
    units: [
      { id: "bit", label: "bit" },
      { id: "byte", label: "byte" },
      { id: "kb", label: "kilobyte (KB)" },
      { id: "mb", label: "megabyte (MB)" },
      { id: "gb", label: "gigabyte (GB)" },
      { id: "tb", label: "terabyte (TB)" },
    ],
  },
];